### ISSUE TITLE
github登录的接口还没有换域名

### ISSUE THREAD

**Issue by yuangu** [WhaleFell/HexoBlogSource#4]
如题，博客的github登录，还是lskyl.xyz域名，

**Comment by WhaleFell** [comment]
好的，已知悉这个 bug 有时间再修复，谢谢。😘

BY WhaleFall
________________________________
From: yuangu ***@***.***>
Sent: Monday, April 24, 2023 4:43:16 PM
To: WhaleFell/HexoBlogSource ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [WhaleFell/HexoBlogSource] github登录的接口还没有换域名 (Issue #4)


如题，博客的github登录，还是lskyl.xyz域名，

**Comment by WhaleFell** [comment]
Already fixed.
